{% set name = "sqlalchemy" %}
{% set version = "2.0.33" %}

package:
  name: sqlalchemy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 91c93333c2b37ff721dc83b37e28c29de4c502b5612f2d093468037b86aa2be0

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=0.29.24                       # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools>=61.0
    - cython >=0.29.24
    - pip
  run:
    - python
    - greenlet !=0.4.17
    - typing-extensions >=4.6.0

test:
  requires:
    - pip
  imports:
    - sqlalchemy
  commands:
    - pip check

about:
  home: https://www.sqlalchemy.org/
  license: MIT
  license_file: LICENSE
  summary: Database Abstraction Library.
  description: |
    SQLAlchemy is the Python SQL toolkit and Object Relational Mapper that
    gives application developers the full power and flexibility of SQL.
  doc_url: https://docs.sqlalchemy.org/
  dev_url: https://github.com/sqlalchemy/sqlalchemy
  doc_source_url: https://github.com/zzzeek/sqlalchemy/blob/master/doc/build/index.rst

extra:
  recipe-maintainers:
    - xylar
    - ocefpaf
    - nehaljwani
    - igortg
