appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: drone, linux_ppc64le: azure, win: azure}
travis:
  secure: {BINSTAR_TOKEN: E0q1N1BgMWNx90s5zijSLeRqq2kg9cm2OSg+ugWpkh3LaAp09LJx9fcCHwgufOwpXQPFHemAhnJZXqGnWviVcuhgnI5J+EW01KFTgFWiXmRibwMftpTU10VptR9Zv2Y8ro5nPBSTMsbfWIucl3aocZdwUggdeQdCA+7B0WF1iWgmJ5CksjtM/R1Ly9AoV0U2yYVlDmtmbtg+ILNKuplDvf7YLXgueLbmMsEAvHPOati8rvju3ArGOuYU2OPwQWv6V4cFT2cqUT53TPd0maNvxZ1pYqBUYxpIR8bCP3kMyK8pvvNmURwhfR9Fet88/pBzbbn8E36a49cYlS5ar69F4LSVQ14H9o+LzwTISyyJ0ng5X78Umw0/44TyBjrnI+QnGmXLZXapT9ALQCuXjwwrGSg/bentpoz3rCNJ745plpAufmk+ONJzzJly5u54x1igYPqzlKLhQIjthh1SiFW0ggiOWgqUTXC+fKrsDzw+REQ7aF8P/JMI8B79KK2YBOVFBqP7dGmus/wwbSfKEzucBBnlix3d+67QA/3tLgFO4WuFB36HwyYVV/D85oDsyrABEKnEySoWGz9rKsGMgisp/PnqvQ5dfZxAufpL+ozf2EHyl7wyaXejCzWvKPSHSNgKAsoYEfs96sm5w7sL4QQOytyZss1EouqwWZHWTnL6e9w=}
